# Generated by Django 5.0.1 on 2024-01-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, default='def.png', null=True, upload_to='book_images/'),
        ),
    ]
